import seedrandom from "seedrandom";

// Export the word list as it is often useful
export const wordList = [
  "accident",
  "managment",
  "mail",
  "rule",
  "talk",
  "teach",
  "team",
  "theory",
  "time",
  "tobacco",
  "tool",
  "travel",
  "transport",
  "war",
  "vegetables",
  "wild",
  "winter",
  "women",
  "won",
  "wood",
  "wool",
  "world",
  "wrapped",
  "write",
  "youth",
  "zipper",
  "zoo",
  "Automation",
  "Data",
  "Analysis",
  "Integration",
  "Cloud",
  "Security",
  "User",
  "Management",
  "Dashboard",
  "Insights",
  "Workflow",
  "Collaboration",
  "API",
  "Sync",
  "Reporting",
  "Metrics",
  "Optimization",
  "Scalability",
  "Notifications",
  "Real-time",
  "Customization",
  "Compliance",
  "Performance",
  "Engagement",
  "Tracking",
  "Support",
  "Templates",
  "Monitoring",
  "Scheduling",
  "Backup",
  "Encryption",
  "Documentation",
  "Feedback",
  "Analytics",
  "CRM",
  "Marketing",
  "Personalization",
  "Authentication",
  "Authorization",
  "Deployment",
  "Versioning",
  "Testing",
  "Provisioning",
  "Load-balancing",
  "Orchestration",
  "Virtualization",
  "Provisioning",
  "Monitoring",
  "Alerting",
  "Incident",
  "Resolution",
  "Discovery",
  "Archiving",
  "Retention",
  "Compression",
  "Logging",
  "Auditing",
  "Cost",
  "Efficiency",
  "Forecasting",
  "Bandwidth",
  "Latency",
  "Availability",
  "Redundancy",
  "Fault-tolerance",
  "Resilience",
  "Throughput",
  "Capacity",
  "Disaster",
  "Recovery",
  "Failover",
  "Load-testing",
  "User-experience",
  "Interface",
  "UX",
  "Design",
  "Accessibility",
  "Responsive",
  "Mobile",
  "Optimization",
  "Browser",
  "Compatibility",
  "SEO",
  "Content",
  "Management",
  "E-commerce",
  "Payment",
  "Gateway",
  "Subscription",
  "Billing",
  "Invoicing",
  "Inventory",
  "Shipping",
  "Order",
  "Fulfillment",
  "Customer",
  "Support",
  "Helpdesk",
  "Ticketing",
  "Service",
  "Level",
  "Agreement",
  "SLA",
  "Knowledge",
  "Base",
  "Self-service",
  "Portal",
  "Virtual-assistant",
  "Chatbot",
  "Artificial",
  "Intelligence",
  "Machine-learning",
  "Deep-learning",
  "NLP",
  "Computer-vision",
  "Big-data",
  "Data-warehouse",
  "Data-lake",
  "ETL",
  "Data-pipeline",
  "Data-mining",
  "Data-visualization",
  "Business-intelligence",
  "Predictive-analytics",
  "Prescriptive-analytics",
  "Robotics",
  "Process-automation",
  "RPA",
  "Internet-of-things",
  "IoT",
  "Edge-computing",
  "Blockchain",
  "Cryptocurrency",
  "Smart-contracts",
  "DeFi",
  "NFT",
  "Augmented-reality",
  "Virtual-reality",
  "Mixed-reality",
  "3D-printing",
  "Wearables",
  "Drones",
  "Autonomous-vehicles",
  "Smart-cities",
  "Green-tech",
  "Sustainability",
  "Energy",
  "Management",
  "Carbon-footprint",
  "Emissions",
  "Tracking",
  "Circular-economy",
  "Telemedicine",
  "Health-tech",
  "Fitness",
  "Wearables",
  "Clinical-trials",
  "Biotech",
  "Genomics",
  "Precision-medicine",
  "Personalized-medicine",
  "Pharmaceutical",
  "Supply-chain",
  "Logistics",
  "Fleet-management",
  "Route-optimization",
  "Warehousing",
  "Inventory",
  "Tracking",
  "Procurement",
  "Supplier",
  "Management",
  "Quality",
  "Control",
  "Compliance",
  "Regulatory",
  "Standards",
  "ISO",
  "GRC",
  "Governance",
  "Risk",
  "Management",
  "Fraud-detection",
  "AML",
  "KYC",
  "Cybersecurity",
  "Threat",
  "Intelligence",
  "Incident",
  "Response",
  "Vulnerability",
  "Management",
  "Penetration-testing",
  "Encryption",
  "Firewalls",
  "IDS",
  "IPS",
  "Network-security",
  "Endpoint-security",
  "SIEM",
  "SOC",
  "Cloud-security",
  "Zero-trust",
  "Access-control",
  "Identity-management",
  "Single-sign-on",
  "SSO",
  "MFA",
  "Password",
  "Management",
  "Data-loss-prevention",
  "DLP",
  "Backup",
  "Disaster-recovery",
  "DRP",
  "Business-continuity",
  "BCP",
  "Asset-management",
  "Configuration",
  "Management",
  "CMDB",
  "Change-management",
  "Incident-management",
  "Problem-management",
  "Service-desk",
  "ITIL",
  "Agile",
  "Scrum",
  "Kanban",
  "DevOps",
  "CI/CD",
  "Continuous-integration",
  "Continuous-delivery",
  "Automation",
  "Infrastructure-code",
  "IaC",
  "Containers",
  "Docker",
  "Kubernetes",
  "Microservices",
  "Serverless",
  "FaaS",
  "API-gateway",
  "Service-mesh",
  "Observability",
  "Monitoring",
  "Logging",
  "Tracing",
  "Metrics",
  "Application-performance",
  "APM",
  "Synthetic-monitoring",
  "Real-user-monitoring",
  "RUM",
  "Digital-experience",
  "Customer-journey",
  "User-analytics",
  "Heatmaps",
  "Session-recording",
  "User-feedback",
  "NPS",
  "CSAT",
  "User-research",
  "Usability-testing",
  "A/B-testing",
  "Multivariate-testing",
  "Feature-flagging",
  "Progressive-delivery",
  "Experimentation",
  "Growth-hacking",
  "Marketing-automation",
  "Email-marketing",
  "Lead-generation",
  "Lead-scoring",
  "CRM",
  "Sales-automation",
  "Sales-pipeline",
  "Opportunity-management",
  "Forecasting",
  "Quoting",
  "Contract-management",
  "Order-management",
  "Subscription-management",
  "Billing",
  "Invoicing",
  "Payment-processing",
  "Accounting",
  "Finance",
  "Financial-planning",
  "Analysis",
  "Treasury",
  "Cash-management",
  "Expense-management",
  "Procure-to-pay",
  "Order-to-cash",
  "Record-to-report",
  "Tax-compliance",
  "Payroll",
  "Human-resources",
  "HR",
  "Talent-management",
  "Recruiting",
  "Applicant-tracking",
  "Onboarding",
  "Learning",
  "Development",
  "Performance-management",
  "Compensation",
  "Benefits",
  "Employee-engagement",
  "Workforce-planning",
  "Workforce-analytics",
  "Labor-compliance",
  "Time",
  "Attendance",
  "Scheduling",
  "Shift-management",
  "Facility-management",
  "Real-estate",
  "Portfolio-management",
  "Lease-management",
  "Energy-management",
  "Space-management",
  "Maintenance",
  "Work-order",
  "Management",
  "Project-management",
  "Task-management",
  "Resource-management",
  "Time-tracking",
  "Collaboration",
  "File-sharing",
  "Document-management",
  "Knowledge-management",
  "Team-communication",
  "Video-conferencing",
  "Web-conferencing",
  "Screen-sharing",
  "Instant-messaging",
  "Group-chat",
  "Forums",
  "Message-boards",
  "Social-intranet",
  "Enterprise-social-network",
  "Employee-recognition",
  "Wellness",
  "Programs",
  "Gamification",
  "E-learning",
  "Online-courses",
  "Virtual-classroom",
  "Webinars",
  "Training",
  "Certification",
  "Compliance-training",
  "Learning-management-system",
  "Content-management-system",
  "Digital-asset-management",
  "Marketing-campaign",
  "Management",
  "Campaign-analytics",
  "Lead-nurturing",
  "Social-media-management",
  "Content-marketing",
  "SEO",
  "Ad-management",
  "Affiliate-marketing",
  "Influencer-marketing",
  "Referral-marketing",
  "Event-marketing",
  "Trade-shows",
  "Conferences",
  "Exhibitions",
  "Customer-experience",
  "Voice-of-the-customer",
  "Customer-insights",
  "Customer-analytics",
  "Customer-data-platform",
  "Customer-support",
  "Contact-center",
  "Call-center",
  "Helpdesk",
  "Ticketing-system",
  "Live-chat",
  "Chatbots",
  "Knowledge-base",
  "Self-service",
  "Customer-portal",
  "Field-service",
  "Management",
  "Dispatch",
  "Scheduling",
  "Mobile-workforce",
  "Asset-tracking",
  "IoT",
  "Healthcare access",
  "Mental health",
  "Telemedicine",
  "Chronic disease management",
  "Elderly care",
  "Fitness tracking",
  "Remote education",
  "E-learning",
  "Skills training",
  "Career counseling",
  "Job matching",
  "Remote work tools",
  "Team collaboration",
  "Productivity enhancement",
  "Project management",
  "Freelancer marketplace",
  "Gig economy",
  "Small business tools",
  "Inventory management",
  "Supply chain optimization",
  "Waste reduction",
  "Recycling",
  "Sustainable packaging",
  "Renewable energy",
  "Electric vehicles",
  "Energy storage",
  "Home automation",
  "Smart home devices",
  "Security systems",
  "Home maintenance",
  "Real estate",
  "Property management",
  "Affordable housing",
  "Urban mobility",
  "Public transportation",
  "Ride-sharing",
  "Last-mile delivery",
  "Food delivery",
  "Grocery delivery",
  "Meal kits",
  "Healthy eating",
  "Diet planning",
  "Nutrition tracking",
  "Food waste",
  "Personal finance",
  "Budgeting",
  "Savings",
  "Investment",
  "Cryptocurrency",
  "Digital banking",
  "Insurance",
  "Credit scoring",
  "Debt management",
  "Legal services",
  "Contract management",
  "Document automation",
  "Tax filing",
  "Accounting services",
  "Climate change",
  "Carbon footprint",
  "Emission tracking",
  "Environmental conservation",
  "Water management",
  "Agriculture technology",
  "Precision farming",
  "Crop monitoring",
  "Pest control",
  "Livestock management",
  "Veterinary services",
  "Pet care",
  "Childcare",
  "Parenting support",
  "Education technology",
  "STEM education",
  "Language learning",
  "Cultural exchange",
  "Travel planning",
  "Adventure tourism",
  "Local experiences",
  "Event management",
  "Virtual events",
  "Community building",
  "Social networking",
  "Mental health",
  "Stress management",
  "Meditation",
  "Sleep improvement",
  "Personal development",
  "Habit tracking",
  "Life coaching",
  "Personal safety",
  "Emergency response",
  "Disaster management",
  "Public health",
  "Vaccination tracking",
  "Infectious disease control",
  "Sanitation",
  "Hygiene",
  "Water purification",
  "Nutrition education",
  "Food security",
  "Hunger relief",
  "Non-profit management",
  "Charity fundraising",
  "Volunteer coordination",
  "Human rights",
  "Social justice",
  "Diversity and inclusion",
  "Women empowerment",
  "LGBTQ+ support",
  "Disability services",
  "Senior citizen support",
  "Youth programs",
  "Animal welfare",
  "Employee onboarding",
  "Shift planning",
  "Performance reviews",
  "Virtual whiteboard",
  "Meeting notes",
  "Document signing",
  "Contract tracking",
  "Task prioritization",
  "Event RSVPs",
  "Online booking",
  "Website analytics",
  "Heatmap tracking",
  "Customer segmentation",
  "Email verification",
  "URL shortener",
  "DNS management",
  "Incident reporting",
  "Bug tracking",
  "Release notes",
  "Feature requests",
  "A/B testing",
  "Content optimization",
  "Influencer analytics",
  "Affiliate tracking",
  "QR code generator",
  "Voice transcription",
  "Web scraping",
  "SEO audit",
  "Content personalization",
  "User onboarding",
  "Behavior analytics",
  "Session replay",
  "Knowledge base",
  "Tutorial builder",
  "Learning management",
  "Team brainstorming",
  "Idea management",
  "Risk assessment",
  "Health monitoring",
  "Symptom checker",
  "Remote support",
  "Virtual concierge",
  "Payment reminders",
  "Invoice generation",
  "Subscription tracking",
  "Refund management",
  "Payroll automation",
  "Tax calculator",
  "Expense reports",
  "Legal compliance",
  "Data encryption",
  "Privacy management",
  "API monitoring",
  "Error logging",
  "Application health",
  "Server uptime",
  "Workflow automation",
  "Lead enrichment",
  "Prospect tracking",
  "Recruitment automation",
  "Talent pipeline",
  "Skill assessment",
  "Training scheduler",
  "Asset tracking",
  "Inventory alerts",
  "Maintenance scheduler",
  "Facility booking",
  "Room reservations",
  "Travel expense management",
  "Fleet tracking",
  "Delivery route optimization",
  "Parcel tracking",
  "Stock alerts",
  "Price monitoring",
  "Competitor analysis",
  "Market research",
  "Trend analysis",
  "Innovation management",
  "Collaboration tools",
  "Partnership management",
  "Virtual networking",
  "Feedback collection",
  "Review aggregation",
  "Reputation management",
  "Client onboarding",
  "Proposal management",
  "Customer journey mapping",
  "Experience management",
  "Product tours",
  "Interactive guides",
  "On-demand support",
  "Live chat",
  "Customer loyalty programs",
  "Referral tracking",
  "Discount management",
  "Membership management",
  "Club management",
  "Event ticketing",
  "Virtual booth management",
  "Exhibitor management",
  "Visitor management",
  "Event check-in",
  "Conference networking",
  "Webinar hosting",
  "Virtual classrooms",
  "Online assessments",
  "Certification tracking",
  "License management",
  "Compliance audits",
  "Safety training",
  "Incident management",
  "First aid training",
  "Safety drills",
  "Crisis management",
  "Public alerts",
  "Crowd management",
  "Traffic management",
  "Pollution monitoring",
  "Resource planning",
  "Community outreach",
  "Volunteer tracking",
  "Donation tracking",
  "Fund management",
  "Grant management",
  "Project fundraising",
];

const shortestWordSize = wordList.reduce((shortestWord, currentWord) =>
  currentWord.length < shortestWord.length ? currentWord : shortestWord
).length;

const longestWordSize = wordList.reduce((longestWord, currentWord) =>
  currentWord.length > longestWord.length ? currentWord : longestWord
).length;

export function generate(options) {
  // initalize random number generator for words if options.seed is provided
  const random = options?.seed ? new seedrandom(options.seed) : null;

  const { minLength, maxLength, ...rest } = options || {};

  function word() {
    let min =
      typeof minLength !== "number"
        ? shortestWordSize
        : limitWordSize(minLength);

    const max =
      typeof maxLength !== "number"
        ? longestWordSize
        : limitWordSize(maxLength);

    if (min > max) min = max;

    let rightSize = false;
    let wordUsed;
    while (!rightSize) {
      wordUsed = generateRandomWord();
      rightSize = wordUsed.length <= max && wordUsed.length >= min;
    }
    return wordUsed;
  }

  function generateRandomWord() {
    return wordList[randInt(wordList.length)];
  }

  // limits the size of words to the minimum and maximum possible
  function limitWordSize(wordSize) {
    if (wordSize < shortestWordSize) wordSize = shortestWordSize;
    if (wordSize > longestWordSize) wordSize = longestWordSize;
    return wordSize;
  }

  // random int as seeded by options.seed if applicable, or Math.random() otherwise
  function randInt(lessThan) {
    const r = random ? random() : Math.random();
    return Math.floor(r * lessThan);
  }

  // No arguments = generate one word
  if (options === undefined) {
    return word();
  }

  // Just a number = return that many words
  if (typeof options === "number") {
    options = { exactly: options };
  } else if (Object.keys(rest).length === 0) {
    return word();
  }

  // options supported: exactly, min, max, join
  if (options.exactly) {
    options.min = options.exactly;
    options.max = options.exactly;
  }

  // not a number = one word par string
  if (typeof options.wordsPerString !== "number") {
    options.wordsPerString = 1;
  }

  //not a function = returns the raw word
  if (typeof options.formatter !== "function") {
    options.formatter = (word) => word;
  }

  //not a string = separator is a space
  if (typeof options.separator !== "string") {
    options.separator = " ";
  }

  const total = options.min + randInt(options.max + 1 - options.min);
  let results = [];
  let token = "";
  let relativeIndex = 0;

  for (let i = 0; i < total * options.wordsPerString; i++) {
    if (relativeIndex === options.wordsPerString - 1) {
      token += options.formatter(word(), relativeIndex);
    } else {
      token += options.formatter(word(), relativeIndex) + options.separator;
    }
    relativeIndex++;
    if ((i + 1) % options.wordsPerString === 0) {
      results.push(token);
      token = "";
      relativeIndex = 0;
    }
  }
  if (typeof options.join === "string") {
    results = results.join(options.join);
  }

  return results;
}

export function count(options) {
  let { minLength, maxLength } = options || {};

  if (typeof minLength !== "number") {
    minLength = shortestWordSize;
  }

  if (typeof maxLength !== "number") {
    maxLength = longestWordSize;
  }

  return wordList.filter(
    (word) => word.length >= minLength && word.length <= maxLength
  ).length;
}
